[package]
name = "mini_cntnr"
version = "0.1.0"
edition = "2021"

[dependencies]
nix={version="0.29.*",features=["sched","fs","mount"]}
thiserror="1.0.37"
log="0.4.17"
simplelog="0.12.0"
anyhow="1.0.66"
libc="0.2.139"
tokio={version="1.28.0",features=["full"]}
